#!/bin/bash
cd scripts
bash fede-git-config.sh
bash vimconfig.sh
bash sshkeys.sh
bash zsh.sh
bash fish.sh
bash fixes.sh
cd linux/ubuntu
bash archiveformats.sh
bash firacode.sh
bash la-capitaine-icons.sh
bash node.sh
bash powerlinefonts.sh
./swap 4G
bash swappiness.sh
bash vscode.sh
bash docker.sh
bash exfat.sh
