#! /bin/sh

bspc config border_width	3
bspc config window_gap		15

bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_follows_pointer true

bspc monitor -d $(echo -e '\uf109') $(echo -e '\uf121') $(echo -e '\uf120') $(echo -e '\uf07c') $(echo -e '\uf0ac') $(echo -e '\uf0c3') $(echo -e '\uf141') $(echo -e '\uf001')

bspc config normal_border_color '#282828'
bspc config focused_border_color '#d5c4a1'
#bspc config presel_border_color '#d79921'
#bspc config normal_sticky_border_color '#1d2021'
#bspc config focused_sticky_border_color '#d5c4a1'
#bspc config urgent_border_color '#cc241d'

bspc rule -a Gimp follow=on floating=on
bspc rule -a mplayer2 floating=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

zsh ~/.local/bin/panel &
# urxvt &
 compton -c -D 4 &
