#!/usr/bin/env sh

#
# wm independent hotkeys
#

# terminal emulator
alt + Return
	termite

# browser
alt + c
	google-chrome-stable

# launcher menu
alt + space
	rofi -show run

# window gap via mouse wheel
# alt + button{4,5}
#    bspc config -d focused window_gap $((`bspc config -d focused window_gap` {+,-} 5))

# sxhkd reload
control + alt + r
	pkill -USR1 -x sxhkd


# Display brightness
control + F6
	xbacklight -dec 10%
control + F7
	xbacklight -inc 10%

# keyboard backlight
control + F5
	~/bin/pixel-keyboard-brightness toggle


# xf86 keys

# XF86AudioMute
control + F8
 	pactl set-sink-mute 0 toggle

# XF86AudioRaiseVolume
control + F9
 	amixer set Master 3%- 
 
# XF86AudioLowerVolume
control + F10
 	amixer set Master 3%+ 

 
XF86MonBrightnessUp
	xbacklight -inc 10%
 
XF86MonBrightnessDown
	xbacklight -dec 10%

# XF86AudioPlay
# 	mpc toggle
# 
# XF86AudioNext
# 	mpc next
# 
# XF86AudioPrev
# 	mpc prev
# 
# XF86KbdBrightnessUp
# 	kbdlight up	
# 
# XF86KbdBrightnessDown
# 	kbdlight down

#
# bspwm hotkeys
#

# quit bspwm
control + alt + Escape
	pkill panel && bspc quit
	bspc quit 1 & pkill panel
 
# close and kill
alt + {_,shift + }q
	bspc node -{c,k}

# alternate between the tiled and monocle layout
alt + m
	bspc desktop -l next

# if the current node is automatic, send it to the last manual, otherwise pull the last leaf
alt + y
	bspc query -N -n focused.automatic && bspc node -n last.!automatic || bspc node last.leaf -n focused

# swap the current node and the biggest node

alt + g
	bspc node -s biggest

#
# state/flags
#

# set the window state
alt + {t,shift + t,s,f}
	bspc node -t '~{tiled,pseudo_tiled,floating,fullscreen}'

# set the node flags
alt + ctrl + {x,y,z}
	bspc node -g {locked,sticky,private}

#
# focus/swap
#

# focus the node in the given direction
super + {_,shift + }{h,j,k,l}
	bspc node -{f,s} {west,south,north,east}

# focus the node for the given path jump
super + {p,b,comma,period}
	bspc node -f @{parent,brother,first,second}

# focus the next/previous node
alt + {_,shift + }c
	bspc node -f {next,prev}

# focus the next/previous desktop
alt + bracket{left,right}
	bspc desktop -f {prev,next}

# focus the last node/desktop
alt + {grave,Tab}
	bspc {node,desktop} -f last

# focus the older or newer node in the focus history
alt + {o,i}
	bspc wm -h off; \
	bspc node {older,newer} -f; \
	bspc wm -h on

# focus or send to the given desktop
alt + {_,shift + }{1-9,0}
	bspc {desktop -f,node -d} '^{1-9,10}'

#
# preselect
#

# preselect the direction
alt + ctrl + {h,j,k,l}
	bspc node -p {west,south,north,east}

# preselect the ratio
alt + ctrl + {1-9}
	bspc node -o 0.{1-9}

# cancel the preselection for the focused node
alt + ctrl + space
	bspc node -p cancel

# cancel the preselection for the focused desktop
alt + ctrl + shift + space
	bspc query -N -d | xargs -I id -n 1 bspc node id -p cancel

#
# resize tiled/floating
#

# expand the tiled space in the given direction
super + alt + {h,j,k,l}
	bspc node {@west -r -10,@south -r +10,@north -r -10,@east -r +10}

# contract the tiled space in the given direction
super + alt + shift + {h,j,k,l}
	bspc node {@east -r -10,@north -r +10,@south -r -10,@west -r +10}

# move a floating window
alt + {Left,Down,Up,Right}
	xdo move {-x -20,-y +20,-y -20,-x +20}

#
# pointer focus/move/resize
#

# focus
~button1
	bspc pointer -g focus

# start move/resize
alt + button{1-3}
	; bspc pointer -g {move,resize_side,resize_corner}

# end move/resize
alt + @button{1-3}
	bspc pointer -u
	
