#!/bin/bash
cd ~/chromebook_keyboard_backlight_driver
make
sudo insmod chromeos_keyboard_leds.ko
sudo insmod chromebook_kb_backlight.ko
sudo cp chromeos_keyboard_leds.ko /lib/modules/3.12.0-031200-generic/
sudo cp chromebook_kb_backlight.ko /lib/modules/3.12.0-031200-generic/
sudo depmod -a
